### ISSUE TITLE
Regression Results comparison

### ISSUE THREAD

**Issue by valebezma** [dcwuser/metanumerics#52]
Since there are several types of regression results were implemented in last release it became hard to choose most appropriate model for my data because of lack of common values between them. Since R squared seems to be incorrect for noninear regressions would it be possible to see regression standard error as a property of basic FitResult class?
I some classes like LinearRR, MultiLinearRR and PolynimialRR it is already calculated as sigma2. It could simply be assigned to that basic property as squared root of sigma2/sigmaSquared.
Residuals list is such a basic feature too. By the way residuals could be implemented as bivariate sample using original x values and resudual y values, which makes it's Y property as currently available Residuals list.

**Comment by dcwuser** [comment]
Added RegressionResult class in hierarchy. All results that return Residuals inherit from it, and it exposes a SumOfSquaredResiduals property.
