### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by cmoncure** [dcwuser/metanumerics#8]
Is there any chance of seeing an official NuGet package supporting netcoreapp1.1?  I was trivially able to clone, create and build the project removing all the code contained within #if !SILVERLIGHT directives.

**Comment by anders9ustafsson** [comment]
Maybe [this](https://metanumerics.codeplex.com/discussions/660878) previous discussion on Codeplex could be of further interest for this request?

**Comment by dcwuser** [comment]
Code now targets .NET Standard 1.1.
